vich_uploader:
    db_driver: orm

    mappings:
        video:
            #uri_prefix: /media
            delete_on_update: false
            inject_on_load: true
            delete_on_remove: true
            upload_destination: '%kernel.project_dir%/public/chunks'
            # Will rename uploaded files using a uniqueid as a prefix.
            namer: Vich\UploaderBundle\Naming\HashNamer